name: Autoupdate VHS Shelf and Inventory

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Generate SVGs
        env:
          GH_USERNAME: ${{ github.repository_owner }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python generate_shelf.py
          python generate_inventory.py
          python generate_about.py

      - name: Commit and Push SVGs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add shelf.svg inventory.svg about.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "update: atualizados svgs do perfil" && git push)
